services:
  - type: web
    name: spotify-downloader-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RAPIDAPI_KEY
        sync: false
      - key: RAPIDAPI_HOST
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: spotify-downloader-frontend
    env: node
    buildCommand: cd project && npm install && npm run build
    startCommand: cd project && npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    autoDeploy: true 